// One-off: node scripts/gen_flores_languages.js
const fs = require('fs');
const path = require('path');

/** FLORES-200 / CTranslate2 NLLB — from OpenNMT docs & facebookresearch/flores */
const ENTRIES = [
  ['Acehnese (Arabic script)', 'ace_Arab'],
  ['Mesopotamian Arabic', 'acm_Arab'],
  ["Ta'izzi-Adeni Arabic", 'acq_Arab'],
  ['Tunisian Arabic', 'aeb_Arab'],
  ['Afrikaans', 'afr_Latn'],
  ['South Levantine Arabic', 'ajp_Arab'],
  ['Akan', 'aka_Latn'],
  ['Amharic', 'amh_Ethi'],
  ['North Levantine Arabic', 'apc_Arab'],
  ['Modern Standard Arabic', 'arb_Arab'],
  ['Najdi Arabic', 'ars_Arab'],
  ['Moroccan Arabic', 'ary_Arab'],
  ['Egyptian Arabic', 'arz_Arab'],
  ['Assamese', 'asm_Beng'],
  ['Asturian', 'ast_Latn'],
  ['Awadhi', 'awa_Deva'],
  ['Central Aymara', 'ayr_Latn'],
  ['North Azerbaijani', 'azj_Latn'],
  ['Bashkir', 'bak_Cyrl'],
  ['Bambara', 'bam_Latn'],
  ['Belarusian', 'bel_Cyrl'],
  ['Bengali', 'ben_Beng'],
  ['Bhojpuri', 'bho_Deva'],
  ['Standard Tibetan', 'bod_Tibt'],
  ['Bosnian', 'bos_Latn'],
  ['Bulgarian', 'bul_Cyrl'],
  ['Catalan', 'cat_Latn'],
  ['Cebuano', 'ceb_Latn'],
  ['Czech', 'ces_Latn'],
  ['Welsh', 'cym_Latn'],
  ['Danish', 'dan_Latn'],
  ['German', 'deu_Latn'],
  ['Greek', 'ell_Grek'],
  ['English', 'eng_Latn'],
  ['Esperanto', 'epo_Latn'],
  ['Estonian', 'est_Latn'],
  ['Basque', 'eus_Latn'],
  ['Finnish', 'fin_Latn'],
  ['French', 'fra_Latn'],
  ['Irish', 'gle_Latn'],
  ['Galician', 'glg_Latn'],
  ['Gujarati', 'guj_Gujr'],
  ['Hausa', 'hau_Latn'],
  ['Hebrew', 'heb_Hebr'],
  ['Hindi', 'hin_Deva'],
  ['Croatian', 'hrv_Latn'],
  ['Hungarian', 'hun_Latn'],
  ['Armenian', 'hye_Armn'],
  ['Igbo', 'ibo_Latn'],
  ['Indonesian', 'ind_Latn'],
  ['Icelandic', 'isl_Latn'],
  ['Italian', 'ita_Latn'],
  ['Japanese', 'jpn_Jpan'],
  ['Javanese', 'jav_Latn'],
  ['Georgian', 'kat_Geor'],
  ['Kazakh', 'kaz_Cyrl'],
  ['Khmer', 'khm_Khmr'],
  ['Kinyarwanda', 'kin_Latn'],
  ['Kyrgyz', 'kir_Cyrl'],
  ['Korean', 'kor_Hang'],
  ['Lao', 'lao_Laoo'],
  ['Lithuanian', 'lit_Latn'],
  ['Luxembourgish', 'ltz_Latn'],
  ['Latvian', 'lvs_Latn'],
  ['Malagasy', 'plt_Latn'],
  ['Maori', 'mri_Latn'],
  ['Macedonian', 'mkd_Cyrl'],
  ['Malayalam', 'mal_Mlym'],
  ['Marathi', 'mar_Deva'],
  ['Mongolian', 'khk_Cyrl'],
  ['Burmese', 'mya_Mymr'],
  ['Dutch', 'nld_Latn'],
  ['Nepali', 'npi_Deva'],
  ['Norwegian Bokmål', 'nob_Latn'],
  ['Chichewa', 'nya_Latn'],
  ['Odia', 'ory_Orya'],
  ['Punjabi', 'pan_Guru'],
  ['Persian', 'pes_Arab'],
  ['Polish', 'pol_Latn'],
  ['Portuguese', 'por_Latn'],
  ['Romanian', 'ron_Latn'],
  ['Russian', 'rus_Cyrl'],
  ['Sanskrit', 'san_Deva'],
  ['Sinhala', 'sin_Sinh'],
  ['Slovak', 'slk_Latn'],
  ['Slovenian', 'slv_Latn'],
  ['Shona', 'sna_Latn'],
  ['Somali', 'som_Latn'],
  ['Albanian', 'als_Latn'],
  ['Serbian', 'srp_Cyrl'],
  ['Sundanese', 'sun_Latn'],
  ['Swedish', 'swe_Latn'],
  ['Swahili', 'swh_Latn'],
  ['Tamil', 'tam_Taml'],
  ['Telugu', 'tel_Telu'],
  ['Tajik', 'tgk_Cyrl'],
  ['Tagalog', 'tgl_Latn'],
  ['Thai', 'tha_Thai'],
  ['Turkish', 'tur_Latn'],
  ['Ukrainian', 'ukr_Cyrl'],
  ['Urdu', 'urd_Arab'],
  ['Uzbek', 'uzn_Latn'],
  ['Vietnamese', 'vie_Latn'],
  ['Wolof', 'wol_Latn'],
  ['Xhosa', 'xho_Latn'],
  ['Yoruba', 'yor_Latn'],
  ['Yue Chinese', 'yue_Hant'],
  ['Chinese (Simplified)', 'zho_Hans'],
  ['Chinese (Traditional)', 'zho_Hant'],
  ['Standard Malay', 'zsm_Latn'],
  ['Zulu', 'zul_Latn'],
];

const ZH = {
  'Chinese (Simplified)': '中文（简体）',
  'Chinese (Traditional)': '中文（繁体）',
  'English': '英语',
  'Russian': '俄语',
  'Japanese': '日语',
  'Korean': '韩语',
  'French': '法语',
  'German': '德语',
  'Spanish': '西班牙语',
  'Modern Standard Arabic': '阿拉伯语',
  'Portuguese': '葡萄牙语',
  'Italian': '意大利语',
  'Dutch': '荷兰语',
  'Polish': '波兰语',
  'Turkish': '土耳其语',
  'Vietnamese': '越南语',
  'Thai': '泰语',
  'Indonesian': '印尼语',
  'Hindi': '印地语',
  'Ukrainian': '乌克兰语',
  'Bengali': '孟加拉语',
  'Tamil': '泰米尔语',
  'Telugu': '泰卢固语',
  'Greek': '希腊语',
  'Hebrew': '希伯来语',
  'Swedish': '瑞典语',
  'Finnish': '芬兰语',
  'Czech': '捷克语',
  'Romanian': '罗马尼亚语',
  'Hungarian': '匈牙利语',
  'Danish': '丹麦语',
  'Norwegian Bokmål': '挪威语',
  'Standard Malay': '马来语',
  'Tagalog': '菲律宾语',
  'Swahili': '斯瓦希里语',
  'Persian': '波斯语',
  'Urdu': '乌尔都语',
  'Punjabi': '旁遮普语',
  'Gujarati': '古吉拉特语',
  'Marathi': '马拉地语',
  'Nepali': '尼泊尔语',
  'Burmese': '缅甸语',
  'Khmer': '高棉语',
  'Lao': '老挝语',
  'Mongolian': '蒙古语',
  'Georgian': '格鲁吉亚语',
  'Armenian': '亚美尼亚语',
  'North Azerbaijani': '阿塞拜疆语',
  'Kazakh': '哈萨克语',
  'Uzbek': '乌兹别克语',
  'Serbian': '塞尔维亚语',
  'Bulgarian': '保加利亚语',
  'Croatian': '克罗地亚语',
  'Slovak': '斯洛伐克语',
  'Slovenian': '斯洛文尼亚语',
  'Lithuanian': '立陶宛语',
  'Latvian': '拉脱维亚语',
  'Estonian': '爱沙尼亚语',
  'Icelandic': '冰岛语',
  'Irish': '爱尔兰语',
  'Welsh': '威尔士语',
  'Basque': '巴斯克语',
  'Catalan': '加泰罗尼亚语',
  'Galician': '加利西亚语',
  'Afrikaans': '南非荷兰语',
  'Zulu': '祖鲁语',
  'Xhosa': '科萨语',
  'Yoruba': '约鲁巴语',
  'Hausa': '豪萨语',
  'Amharic': '阿姆哈拉语',
  'Somali': '索马里语',
  'Malagasy': '马达加斯加语',
  'Esperanto': '世界语',
  'Yue Chinese': '粤语',
  'Acehnese (Arabic script)': '亚齐语（阿拉伯文）',
  'Mesopotamian Arabic': '美索不达米亚阿拉伯语',
  "Ta'izzi-Adeni Arabic": '塔伊兹-亚丁阿拉伯语',
  'Tunisian Arabic': '突尼斯阿拉伯语',
  'South Levantine Arabic': '南黎凡特阿拉伯语',
  'Akan': '阿坎语',
  'North Levantine Arabic': '北黎凡特阿拉伯语',
  'Najdi Arabic': '内志阿拉伯语',
  'Moroccan Arabic': '摩洛哥阿拉伯语',
  'Egyptian Arabic': '埃及阿拉伯语',
  'Assamese': '阿萨姆语',
  'Asturian': '阿斯图里亚斯语',
  'Awadhi': '阿瓦德语',
  'Central Aymara': '中部艾马拉语',
  'Bashkir': '巴什基尔语',
  'Bambara': '班巴拉语',
  'Belarusian': '白俄罗斯语',
  'Bhojpuri': '博杰普尔语',
  'Standard Tibetan': '藏语',
  'Bosnian': '波斯尼亚语',
  'Cebuano': '宿务语',
  'Igbo': '伊博语',
  'Javanese': '爪哇语',
  'Kinyarwanda': '卢旺达语',
  'Kyrgyz': '吉尔吉斯语',
  'Luxembourgish': '卢森堡语',
  'Maori': '毛利语',
  'Macedonian': '马其顿语',
  'Malayalam': '马拉雅拉姆语',
  'Chichewa': '齐切瓦语',
  'Odia': '奥里亚语',
  'Sanskrit': '梵语',
  'Sinhala': '僧伽罗语',
  'Shona': '绍纳语',
  'Sundanese': '巽他语',
  'Tajik': '塔吉克语',
  'Wolof': '沃洛夫语',
  'Albanian': '阿尔巴尼亚语',
};

const ISO = {
  zho_Hans: 'zh',
  zho_Hant: 'zh-Hant',
  eng_Latn: 'en',
  rus_Cyrl: 'ru',
  jpn_Jpan: 'ja',
  kor_Hang: 'ko',
  fra_Latn: 'fr',
  deu_Latn: 'de',
  spa_Latn: 'es',
  arb_Arab: 'ar',
  por_Latn: 'pt',
  ita_Latn: 'it',
  nld_Latn: 'nl',
  pol_Latn: 'pl',
  tur_Latn: 'tr',
  vie_Latn: 'vi',
  tha_Thai: 'th',
  ind_Latn: 'id',
  hin_Deva: 'hi',
  ukr_Cyrl: 'uk',
};

const items = ENTRIES.map(([en, code]) => ({
  nllbCode: code,
  label: ZH[en] || en,
  isoCode: ISO[code] || code.split('_')[0],
}));
items.sort((a, b) => a.label.localeCompare(b.label, 'zh'));

const out = path.join(__dirname, '../entry/src/main/resources/rawfile/flores200_languages.json');
fs.mkdirSync(path.dirname(out), { recursive: true });
fs.writeFileSync(out, JSON.stringify(items));
console.log('Wrote', items.length, 'languages to', out);
