# SummerTTS (MIT) — Chinese offline TTS sources for HarmonyOS NAPI
set(SUMMERTTS_CPP_SOURCES
    ${SUMMERTTS_ROOT}/src/tn/glog/src/demangle.cc
    ${SUMMERTTS_ROOT}/src/tn/glog/src/logging.cc
    ${SUMMERTTS_ROOT}/src/tn/glog/src/raw_logging.cc
    ${SUMMERTTS_ROOT}/src/tn/glog/src/symbolize.cc
    ${SUMMERTTS_ROOT}/src/tn/glog/src/utilities.cc
    ${SUMMERTTS_ROOT}/src/tn/glog/src/vlog_is_on.cc
    ${SUMMERTTS_ROOT}/src/tn/glog/src/signalhandler.cc
    ${SUMMERTTS_ROOT}/src/tn/gflags/src/gflags.cc
    ${SUMMERTTS_ROOT}/src/tn/gflags/src/gflags_reporting.cc
    ${SUMMERTTS_ROOT}/src/tn/gflags/src/gflags_completions.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/compat.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/flags.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/fst.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/fst-types.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/mapped-file.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/properties.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/symbol-table.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/symbol-table-ops.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/util.cc
    ${SUMMERTTS_ROOT}/src/tn/openfst/src/lib/weight.cc
    ${SUMMERTTS_ROOT}/src/tn/processor.cc
    ${SUMMERTTS_ROOT}/src/tn/token_parser.cc
    ${SUMMERTTS_ROOT}/src/tn/utf8_string.cc
    ${SUMMERTTS_ROOT}/src/engipa/EnglishText2Id.cpp
    ${SUMMERTTS_ROOT}/src/engipa/InitIPASymbols.cpp
    ${SUMMERTTS_ROOT}/src/engipa/alphabet.cpp
    ${SUMMERTTS_ROOT}/src/engipa/ipa.cpp
    ${SUMMERTTS_ROOT}/src/hz2py/hanzi2phoneid.cpp
    ${SUMMERTTS_ROOT}/src/hz2py/Hanz2Piny.cpp
    ${SUMMERTTS_ROOT}/src/hz2py/pinyinmap.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_conv1d.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_softmax.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_layer_norm.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_relu.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_gelu.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_tanh.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_flip.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_cumsum.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_softplus.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_clamp_min.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_sigmoid.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_conv1d_transposed.cpp
    ${SUMMERTTS_ROOT}/src/nn_op/nn_leaky_relu.cpp
    ${SUMMERTTS_ROOT}/src/platform/tts_file_io.cpp
    ${SUMMERTTS_ROOT}/src/platform/tts_logger.cpp
    ${SUMMERTTS_ROOT}/src/utils/utils.cpp
    ${SUMMERTTS_ROOT}/src/modules/iStft.cpp
    ${SUMMERTTS_ROOT}/src/modules/hann.cpp
    ${SUMMERTTS_ROOT}/src/modules/attention_encoder.cpp
    ${SUMMERTTS_ROOT}/src/modules/multi_head_attention.cpp
    ${SUMMERTTS_ROOT}/src/modules/ffn.cpp
    ${SUMMERTTS_ROOT}/src/modules/ConvFlow.cpp
    ${SUMMERTTS_ROOT}/src/modules/DDSConv.cpp
    ${SUMMERTTS_ROOT}/src/modules/ElementwiseAffine.cpp
    ${SUMMERTTS_ROOT}/src/modules/random_gen.cpp
    ${SUMMERTTS_ROOT}/src/modules/ResidualCouplingLayer.cpp
    ${SUMMERTTS_ROOT}/src/modules/ResBlock1.cpp
    ${SUMMERTTS_ROOT}/src/modules/WN.cpp
    ${SUMMERTTS_ROOT}/src/modules/pqmf.cpp
    ${SUMMERTTS_ROOT}/src/models/TextEncoder.cpp
    ${SUMMERTTS_ROOT}/src/models/StochasticDurationPredictor.cpp
    ${SUMMERTTS_ROOT}/src/models/FixDurationPredictor.cpp
    ${SUMMERTTS_ROOT}/src/models/DurationPredictor_base.cpp
    ${SUMMERTTS_ROOT}/src/models/ResidualCouplingBlock.cpp
    ${SUMMERTTS_ROOT}/src/models/Generator_base.cpp
    ${SUMMERTTS_ROOT}/src/models/Generator_hifigan.cpp
    ${SUMMERTTS_ROOT}/src/models/Generator_MS.cpp
    ${SUMMERTTS_ROOT}/src/models/Generator_Istft.cpp
    ${SUMMERTTS_ROOT}/src/models/Generator_MBB.cpp
    ${SUMMERTTS_ROOT}/src/models/SynthesizerTrn.cpp
)
